### PR TITLE
Update dockerfile and deploy scripts

### PR DESCRIPTION
**Pull request by JimmyKuruvilla**
The rationale for updating the dockerfile is : 
If I'm going to update any part of it, we may as well just use our own since it is so simple and we have no need for java etc. The swagger dockerfile also takes a while to build fresh. The updated docker file uses the same image as web so it will save some time on local dev and space on jenkins, and also allows for consistency between our jenkins jobs. 

The gulp job was running as root in the container meaning the env file was owned by root and so could not be overwritten by the `deploy_dev.sh` script. Running gulp as a standard user in the container does work locally, but for some reason the permissions for the directory were not getting set correctly on jenkins. I didn't bother to figure out why.

So instead of changing the env file's permissions to match this atypical deployment procedure, I 
1. removed the env.js copy task out of gulp (now must be done manually once on local repo setup)
2. had the deploy script handle overwriting the env file.
3. dist directory and some css files were being tracked that were being modified every `gulp`. Since those files are created by root, jenkins couldn't clone over them so builds after the first were failing.

### CODE REVIEW

**Comment by 23will** [comment]
👍 WNBC, be cleaner to move the Dockerfile into it's own `docker` dir so we can remove the ineffective docker ignore file

**Comment by frosforever** [comment]
What am I missing here? This seems to be much more than just a Dockerfile update. What's with all the removal of stuff?

**Comment by 23will** [comment]
👍 @frosforever they files in the `dist` directory that shouldn't be there in the first place

**Comment by frosforever** [comment]
👍

**Pull request merged**
